apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: DataTeam
  namespace: datateam
spec:
  interval: 5m
  url: https://github.com/Zero-Foxtrot/DataTeam
  ref:
    branch: main
