apiVersion: v1
kind: Service
metadata:
    name: "datateam-6034"
    labels:
        app: "datateam-6034"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "datateam-6034"