on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: btrustengdata.azurecr.io
        username: ${{ secrets.acr_btrustengdata_username }}
        password: ${{ secrets.acr_btrustengdata_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t btrustengdata.azurecr.io/datateam:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push btrustengdata.azurecr.io/datateam:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_datateam_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep datateam | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace datateam`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: datateam
        container-registry-url: btrustengdata.azurecr.io
        container-registry-username: ${{ secrets.acr_btrustengdata_username }}
        container-registry-password: ${{ secrets.acr_btrustengdata_password }}
        secret-name: datateamdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: datateam
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          btrustengdata.azurecr.io/datateam:${{ github.sha }}
        imagepullsecrets: |
          datateamdockerauth
